!io
version: 0
type: xml
param_root: !list
  objects: {}
  lists:
    ConfigRoot: !list
      objects:
        AttackTypeImpulseData: !obj
          ImpulseUseRate: 0.6
          ImpulsePower: 1200.0
          LargeAttackRate: 2.5
          BlastOffAttackRateSmall: 1.0
          BlastOffAttackRateLarge: 4.0
          SpecialAttackRate: 5.0
      lists:
        ImpactImpulseInfo01: !list
          objects: {}
          lists:
            PartImpulseInfo01: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 Ragdoll_Head, DivideFlag: false,
                  ImpulseRate: 0.6, DivideRate: 0.5}
                ReceiveObj02: !obj {TypeName: !str64 Ragdoll_Spine_2, DivideFlag: false,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ReceiveObj03: !obj {TypeName: !str64 Ragdoll_Spine_2, DivideFlag: false,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.524, -1.0]
                  AttackPoint: !vec3 [0.0, 1.11, 0.0]
                  ImpulsePower: 5000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Neck
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.5, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 5000.0
                ImpulseObj03: !obj
                  TypeName: !str64 Ragdoll_Spine_2
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -1.0, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 10000.0
                ImpulseObj04: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                ImpulseObj05: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                PartImpulseData: !obj {IsUseReceiveImpulse: true, IsUseFixedImpulse: true}
              lists: {}
            PartImpulseInfo02: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 Ragdoll_Head, DivideFlag: false,
                  ImpulseRate: 0.6, DivideRate: 0.5}
                ReceiveObj02: !obj {TypeName: !str64 Ragdoll_Spine_2, DivideFlag: false,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ReceiveObj03: !obj {TypeName: !str64 Ragdoll_Spine_2, DivideFlag: false,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.524, -1.0]
                  AttackPoint: !vec3 [0.0, 1.11, 0.0]
                  ImpulsePower: 5000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Neck
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.5, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 5000.0
                ImpulseObj03: !obj
                  TypeName: !str64 Ragdoll_Spine_2
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -1.0, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 10000.0
                ImpulseObj04: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                ImpulseObj05: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                PartImpulseData: !obj {IsUseReceiveImpulse: true, IsUseFixedImpulse: true}
              lists: {}
            PartImpulseInfo03: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 Ragdoll_Spine_2, DivideFlag: true,
                  ImpulseRate: 0.5, DivideRate: 0.5}
                ReceiveObj02: !obj {TypeName: !str64 Ragdoll_Skl_Root, DivideFlag: false,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ReceiveObj03: !obj {TypeName: !str64 Ragdoll_Head, DivideFlag: true,
                  ImpulseRate: 0.5, DivideRate: 0.5}
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Spine_2
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -0.536, 1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 5000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -0.682, 1.0]
                  AttackPoint: !vec3 [0.0, 1.01, 0.0]
                  ImpulsePower: 3500.0
                ImpulseObj03: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.05, 0.0, 1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 250.0
                ImpulseObj04: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [-0.05, 0.0, 1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 250.0
                ImpulseObj05: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                PartImpulseData: !obj {IsUseReceiveImpulse: true, IsUseFixedImpulse: true}
              lists: {}
        ImpactImpulseInfo02: !list
          objects: {}
          lists:
            PartImpulseInfo01: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 Ragdoll_Head, DivideFlag: true,
                  ImpulseRate: 0.8, DivideRate: 0.5}
                ReceiveObj02: !obj {TypeName: !str64 Ragdoll_Head, DivideFlag: true,
                  ImpulseRate: 0.5, DivideRate: 0.5}
                ReceiveObj03: !obj {TypeName: !str64 Ragdoll_Spine_2, DivideFlag: false,
                  ImpulseRate: 0.5, DivideRate: 0.5}
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 1.0, -0.068]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 1000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.2, -0.158]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3000.0
                ImpulseObj03: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                ImpulseObj04: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                ImpulseObj05: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                PartImpulseData: !obj {IsUseReceiveImpulse: true, IsUseFixedImpulse: true}
              lists: {}
            PartImpulseInfo02: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 Ragdoll_Head, DivideFlag: true,
                  ImpulseRate: 0.8, DivideRate: 0.5}
                ReceiveObj02: !obj {TypeName: !str64 Ragdoll_Head, DivideFlag: true,
                  ImpulseRate: 0.5, DivideRate: 0.5}
                ReceiveObj03: !obj {TypeName: !str64 Ragdoll_Spine_2, DivideFlag: false,
                  ImpulseRate: 0.5, DivideRate: 0.5}
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 1.0, -0.068]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 1000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.2, -0.158]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3000.0
                ImpulseObj03: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                ImpulseObj04: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                ImpulseObj05: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                PartImpulseData: !obj {IsUseReceiveImpulse: true, IsUseFixedImpulse: true}
              lists: {}
            PartImpulseInfo03: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 Ragdoll_Skl_Root, DivideFlag: false,
                  ImpulseRate: 0.75, DivideRate: 0.75}
                ReceiveObj02: !obj {TypeName: !str64 Ragdoll_Skl_Root, DivideFlag: false,
                  ImpulseRate: 0.75, DivideRate: 0.75}
                ReceiveObj03: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 1.0,
                  DivideRate: 0.5}
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.0, -0.1]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 300.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Leg_2_R
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, -0.1]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 300.0
                ImpulseObj03: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.45, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 400.0
                ImpulseObj04: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 1.0, -0.65]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 400.0
                ImpulseObj05: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                PartImpulseData: !obj {IsUseReceiveImpulse: true, IsUseFixedImpulse: true}
              lists: {}
