!io
version: 0
type: xml
param_root: !list
  objects: {}
  lists:
    ConfigRoot: !list
      objects:
        AttackTypeImpulseData: !obj
          ImpulseUseRate: 0.5
          ImpulsePower: 120.0
          LargeAttackRate: 1.0
          BlastOffAttackRateSmall: 1.0
          BlastOffAttackRateLarge: 1.0
          SpecialAttackRate: 1.0
      lists:
        ImpactImpulseInfo01: !list
          objects: {}
          lists:
            PartImpulseInfo01: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 Ragdoll_Spine_1, DivideFlag: false,
                  ImpulseRate: 0.5, DivideRate: 0.5}
                ReceiveObj02: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 1.0,
                  DivideRate: 0.5}
                ReceiveObj03: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 1.0,
                  DivideRate: 0.5}
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.35, -0.25]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.35, -0.25]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 1000.0
                ImpulseObj03: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                ImpulseObj04: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                ImpulseObj05: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                PartImpulseData: !obj {IsUseReceiveImpulse: true, IsUseFixedImpulse: true}
              lists: {}
            PartImpulseInfo02: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 Ragdoll_Spine_1, DivideFlag: false,
                  ImpulseRate: 0.5, DivideRate: 0.5}
                ReceiveObj02: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 1.0,
                  DivideRate: 0.5}
                ReceiveObj03: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 1.0,
                  DivideRate: 0.5}
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.3, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 6000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: false
                  AttackVector: !vec3 [0.0, -1.0, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 500.0
                ImpulseObj03: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.05, 0.0, 1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 250.0
                ImpulseObj04: !obj
                  TypeName: !str64 Ragdoll_Leg_2_R
                  UseFlag: false
                  AttackVector: !vec3 [-0.05, 0.0, 1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 250.0
                ImpulseObj05: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                PartImpulseData: !obj {IsUseReceiveImpulse: true, IsUseFixedImpulse: true}
              lists: {}
            PartImpulseInfo03: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 Ragdoll_Spine_1, DivideFlag: false,
                  ImpulseRate: 0.6, DivideRate: 0.5}
                ReceiveObj02: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 0.5,
                  DivideRate: 0.5}
                ReceiveObj03: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 1.0,
                  DivideRate: 0.5}
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Leg_2_L
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 2000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Leg_2_R
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 2000.0
                ImpulseObj03: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.75, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3500.0
                ImpulseObj04: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 1.0, -0.162]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 800.0
                ImpulseObj05: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                PartImpulseData: !obj {IsUseReceiveImpulse: true, IsUseFixedImpulse: true}
              lists: {}
        ImpactImpulseInfo02: !list
          objects: {}
          lists:
            PartImpulseInfo01: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 Ragdoll_Head, DivideFlag: true,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ReceiveObj02: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 1.0,
                  DivideRate: 0.5}
                ReceiveObj03: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 1.0,
                  DivideRate: 0.5}
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, -1.0, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 5000.0
                ImpulseObj02: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                ImpulseObj03: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                ImpulseObj04: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                ImpulseObj05: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                PartImpulseData: !obj {IsUseReceiveImpulse: true, IsUseFixedImpulse: true}
              lists: {}
            PartImpulseInfo02: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 Ragdoll_Spine_1, DivideFlag: true,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ReceiveObj02: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 1.0,
                  DivideRate: 0.5}
                ReceiveObj03: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 1.0,
                  DivideRate: 0.5}
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Skl_Root
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 1.0, -1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.346, -0.142]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 110.0
                ImpulseObj03: !obj
                  TypeName: !str64 Ragdoll_Leg_2_L
                  UseFlag: true
                  AttackVector: !vec3 [0.05, 0.0, 1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 250.0
                ImpulseObj04: !obj
                  TypeName: !str64 Ragdoll_Leg_2_R
                  UseFlag: true
                  AttackVector: !vec3 [-0.05, 0.0, 1.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 250.0
                ImpulseObj05: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                PartImpulseData: !obj {IsUseReceiveImpulse: true, IsUseFixedImpulse: true}
              lists: {}
            PartImpulseInfo03: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 Ragdoll_Leg_2_R, DivideFlag: true,
                  ImpulseRate: 0.5, DivideRate: 0.5}
                ReceiveObj02: !obj {TypeName: !str64 Ragdoll_Leg_2_L, DivideFlag: true,
                  ImpulseRate: 0.5, DivideRate: 0.5}
                ReceiveObj03: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 1.0,
                  DivideRate: 0.5}
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Leg_2_L
                  UseFlag: true
                  AttackVector: !vec3 [-1.0, 0.152, -0.096]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 300.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Leg_2_R
                  UseFlag: true
                  AttackVector: !vec3 [-1.0, 0.152, -0.092]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 300.0
                ImpulseObj03: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.828, 0.75, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 2000.0
                ImpulseObj04: !obj
                  TypeName: !str64 Ragdoll_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 1.0, -0.162]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 800.0
                ImpulseObj05: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                PartImpulseData: !obj {IsUseReceiveImpulse: true, IsUseFixedImpulse: true}
              lists: {}
