!io
version: 0
type: xml
param_root: !list
  objects: {}
  lists:
    ConfigRoot: !list
      objects:
        AttackTypeImpulseData: !obj
          ImpulseUseRate: 0.7
          ImpulsePower: 1200.0
          LargeAttackRate: 2.5
          BlastOffAttackRateSmall: 3.0
          BlastOffAttackRateLarge: 3.0
          SpecialAttackRate: 4.0
      lists:
        ImpactImpulseInfo01: !list
          objects: {}
          lists:
            PartImpulseInfo01: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 Ragdoll_Head, DivideFlag: false,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ReceiveObj02: !obj {TypeName: !str64 Ragdoll_Head, DivideFlag: false,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ReceiveObj03: !obj {TypeName: !str64 Ragdoll_Man_Spine_2, DivideFlag: false,
                  ImpulseRate: 0.8, DivideRate: 0.5}
                ImpulseObj01: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.468, -0.542]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Man_Spine_2
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.626, -0.666]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 2000.0
                ImpulseObj03: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                ImpulseObj04: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                ImpulseObj05: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                PartImpulseData: !obj {IsUseReceiveImpulse: true, IsUseFixedImpulse: true}
              lists: {}
            PartImpulseInfo02: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 Ragdoll_Head, DivideFlag: false,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ReceiveObj02: !obj {TypeName: !str64 Ragdoll_Head, DivideFlag: false,
                  ImpulseRate: 0.6, DivideRate: 0.5}
                ReceiveObj03: !obj {TypeName: !str64 Ragdoll_Man_Spine_2, DivideFlag: false,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ImpulseObj01: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.468, -0.542]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Man_Spine_2
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.626, -0.666]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 4000.0
                ImpulseObj03: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                ImpulseObj04: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                ImpulseObj05: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                PartImpulseData: !obj {IsUseReceiveImpulse: true, IsUseFixedImpulse: true}
              lists: {}
            PartImpulseInfo03: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 Ragdoll_Head, DivideFlag: false,
                  ImpulseRate: 0.8, DivideRate: 0.5}
                ReceiveObj02: !obj {TypeName: !str64 Ragdoll_Head, DivideFlag: false,
                  ImpulseRate: 0.5, DivideRate: 0.5}
                ReceiveObj03: !obj {TypeName: !str64 Ragdoll_Man_Spine_2, DivideFlag: false,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ImpulseObj01: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.468, -0.542]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Man_Spine_2
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.626, -0.666]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3000.0
                ImpulseObj03: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                ImpulseObj04: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                ImpulseObj05: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                PartImpulseData: !obj {IsUseReceiveImpulse: true, IsUseFixedImpulse: true}
              lists: {}
        ImpactImpulseInfo02: !list
          objects: {}
          lists:
            PartImpulseInfo01: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 Ragdoll_Head, DivideFlag: false,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ReceiveObj02: !obj {TypeName: !str64 Ragdoll_Head, DivideFlag: false,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ReceiveObj03: !obj {TypeName: !str64 Ragdoll_Man_Spine_1, DivideFlag: false,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 1.0, -0.608]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 6000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Man_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.2, -0.158]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3000.0
                ImpulseObj03: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.296, -0.286]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 8000.0
                ImpulseObj04: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                ImpulseObj05: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                PartImpulseData: !obj {IsUseReceiveImpulse: true, IsUseFixedImpulse: true}
              lists: {}
            PartImpulseInfo02: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 Ragdoll_Head, DivideFlag: false,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ReceiveObj02: !obj {TypeName: !str64 Ragdoll_Head, DivideFlag: false,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ReceiveObj03: !obj {TypeName: !str64 Ragdoll_Man_Spine_1, DivideFlag: false,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 1.0, -0.608]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 6000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Man_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.2, -0.158]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3000.0
                ImpulseObj03: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.296, -0.286]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 8000.0
                ImpulseObj04: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                ImpulseObj05: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                PartImpulseData: !obj {IsUseReceiveImpulse: true, IsUseFixedImpulse: true}
              lists: {}
            PartImpulseInfo03: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 Ragdoll_Head, DivideFlag: false,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ReceiveObj02: !obj {TypeName: !str64 Ragdoll_Head, DivideFlag: false,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ReceiveObj03: !obj {TypeName: !str64 Ragdoll_Man_Spine_1, DivideFlag: false,
                  ImpulseRate: 1.0, DivideRate: 0.5}
                ImpulseObj01: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 1.0, -0.608]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 6000.0
                ImpulseObj02: !obj
                  TypeName: !str64 Ragdoll_Man_Spine_1
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.2, -0.158]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 3000.0
                ImpulseObj03: !obj
                  TypeName: !str64 Ragdoll_Head
                  UseFlag: true
                  AttackVector: !vec3 [0.0, 0.296, -0.286]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 8000.0
                ImpulseObj04: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                ImpulseObj05: !obj
                  TypeName: !str64 
                  UseFlag: false
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.1
                PartImpulseData: !obj {IsUseReceiveImpulse: true, IsUseFixedImpulse: true}
              lists: {}
