!io
version: 0
type: xml
param_root: !list
  objects:
    CommonData: !obj {UpperLimitHight: 0.06, LowerLimitHight: -0.6}
  lists:
    ImpulseParamList: !list
      objects:
        ImpulseParam_Default: !obj {FileName: !str64 Bokoblin_Red_Default}
        ImpulseParam_Sword: !obj {FileName: !str64 Bokoblin_Red_Sword}
        ImpulseParam_LargeSword: !obj {FileName: !str64 Bokoblin_Red_LargeSword}
        ImpulseParam_Spear: !obj {FileName: !str64 Bokoblin_Red_Spear}
        ImpulseParam_Arrow: !obj {FileName: !str64 Bokoblin_Red_Arrow}
        ImpulseParam_Bomb: !obj {FileName: !str64 Bokoblin_Red_Bomb}
        ImpulseParam_HeadShot: !obj {FileName: !str64 Bokoblin_Red_HeadShot}
        ImpulseParam_ShockWave: !obj {FileName: !str64 Bokoblin_Red_ShockWave}
        ImpulseParam_SilentKill: !obj {FileName: !str64 Bokoblin_Red_SilentKill}
        ImpulseParam_Gust: !obj {FileName: !str64 Bokoblin_Red_Gust}
      lists: {}
    BodyParamList: !list
      objects:
        BodyParam_0: !obj {RigidName: !str64 Ragdoll_Ankle_L, FrictionScale: 0.75,
          BuoyancyScale: 1.0}
        BodyParam_1: !obj {RigidName: !str64 Ragdoll_Ankle_R, FrictionScale: 0.75,
          BuoyancyScale: 1.0}
        BodyParam_2: !obj {RigidName: !str64 Ragdoll_Arm_1_L, FrictionScale: 0.5,
          BuoyancyScale: 0.25}
        BodyParam_3: !obj {RigidName: !str64 Ragdoll_Arm_1_R, FrictionScale: 0.5,
          BuoyancyScale: 0.25}
        BodyParam_4: !obj {RigidName: !str64 Ragdoll_Arm_2_L, FrictionScale: 0.5,
          BuoyancyScale: 0.25}
        BodyParam_5: !obj {RigidName: !str64 Ragdoll_Arm_2_R, FrictionScale: 0.5,
          BuoyancyScale: 0.25}
        BodyParam_6: !obj {RigidName: !str64 Ragdoll_Head, FrictionScale: 1.0, BuoyancyScale: 0.25}
        BodyParam_7: !obj {RigidName: !str64 Ragdoll_Leg_1_L, FrictionScale: 0.75,
          BuoyancyScale: 0.5}
        BodyParam_8: !obj {RigidName: !str64 Ragdoll_Leg_1_R, FrictionScale: 0.75,
          BuoyancyScale: 0.5}
        BodyParam_9: !obj {RigidName: !str64 Ragdoll_Leg_2_L, FrictionScale: 0.75,
          BuoyancyScale: 0.5}
        BodyParam_10: !obj {RigidName: !str64 Ragdoll_Leg_2_R, FrictionScale: 0.75,
          BuoyancyScale: 0.5}
        BodyParam_11: !obj {RigidName: !str64 Ragdoll_Skl_Root, FrictionScale: 1.0,
          BuoyancyScale: 0.75}
        BodyParam_12: !obj {RigidName: !str64 Ragdoll_Spine_1, FrictionScale: 1.0,
          BuoyancyScale: 0.5}
        BodyParam_13: !obj {RigidName: !str64 Ragdoll_Weapon_R, FrictionScale: 1.0,
          BuoyancyScale: 1.0}
        BodyParam_14: !obj {RigidName: !str64 Ragdoll_Wrist_L, FrictionScale: 0.5,
          BuoyancyScale: 0.5}
        BodyParam_15: !obj {RigidName: !str64 Ragdoll_Wrist_R, FrictionScale: 0.5,
          BuoyancyScale: 0.5}
      lists: {}
