!io
version: 0
type: xml
param_root: !list
  objects:
    CommonData: !obj {UpperLimitHight: 1.0, LowerLimitHight: -0.65}
  lists:
    ImpulseParamList: !list
      objects:
        ImpulseParam_Default: !obj {FileName: !str64 Enemy_SiteBoss_Bow_Default}
        ImpulseParam_Sword: !obj {FileName: !str64 Enemy_SiteBoss_Bow_Sword}
        ImpulseParam_LargeSword: !obj {FileName: !str64 Enemy_SiteBoss_Bow_LargeSword}
        ImpulseParam_Spear: !obj {FileName: !str64 Enemy_SiteBoss_Bow_Spear}
        ImpulseParam_Arrow: !obj {FileName: !str64 Enemy_SiteBoss_Bow_Arrow}
        ImpulseParam_Bomb: !obj {FileName: !str64 Enemy_SiteBoss_Bow_Bomb}
        ImpulseParam_ShockWave: !obj {FileName: !str64 Enemy_SiteBoss_Bow_ShockWave}
        ImpulseParam_HeadShot: !obj {FileName: !str64 Enemy_SiteBoss_Bow_HeadShot}
      lists: {}
    BodyParamList: !list
      objects:
        BodyParam_0: !obj {RigidName: !str64 Ragdoll_Arm_1_L, FrictionScale: 0.5,
          BuoyancyScale: 1.0}
        BodyParam_1: !obj {RigidName: !str64 Ragdoll_Arm_1_R, FrictionScale: 0.5,
          BuoyancyScale: 1.0}
        BodyParam_2: !obj {RigidName: !str64 Ragdoll_Arm_2_L, FrictionScale: 0.5,
          BuoyancyScale: 1.0}
        BodyParam_3: !obj {RigidName: !str64 Ragdoll_Arm_2_R, FrictionScale: 0.5,
          BuoyancyScale: 1.0}
        BodyParam_4: !obj {RigidName: !str64 Ragdoll_Head, FrictionScale: 0.6, BuoyancyScale: 1.0}
        BodyParam_5: !obj {RigidName: !str64 Ragdoll_Neck, FrictionScale: 0.6, BuoyancyScale: 1.0}
        BodyParam_6: !obj {RigidName: !str64 Ragdoll_Skl_Root, FrictionScale: 0.6,
          BuoyancyScale: 1.0}
        BodyParam_7: !obj {RigidName: !str64 Ragdoll_Spine_1, FrictionScale: 0.6,
          BuoyancyScale: 1.0}
        BodyParam_8: !obj {RigidName: !str64 Ragdoll_Spine_2, FrictionScale: 0.6,
          BuoyancyScale: 1.0}
        BodyParam_9: !obj {RigidName: !str64 Ragdoll_Wrist_L, FrictionScale: 0.5,
          BuoyancyScale: 1.0}
      lists: {}
