!io
version: 0
type: xml
param_root: !list
  objects:
    CommonData: !obj {UpperLimitHight: 0.2, LowerLimitHight: -0.25}
  lists:
    ImpulseParamList: !list
      objects:
        ImpulseParam_Default: !obj {FileName: !str64 Enemy_SiteBoss_Sword_Default}
        ImpulseParam_Sword: !obj {FileName: !str64 Enemy_SiteBoss_Sword_Sword}
        ImpulseParam_LargeSword: !obj {FileName: !str64 Enemy_SiteBoss_Sword_LargeSword}
        ImpulseParam_Spear: !obj {FileName: !str64 Enemy_SiteBoss_Sword_Spear}
        ImpulseParam_Arrow: !obj {FileName: !str64 Enemy_SiteBoss_Sword_Arrow}
        ImpulseParam_Bomb: !obj {FileName: !str64 Enemy_SiteBoss_Sword_Bomb}
        ImpulseParam_ShockWave: !obj {FileName: !str64 Enemy_SiteBoss_Sword_ShockWave}
        ImpulseParam_HeadShot: !obj {FileName: !str64 Enemy_SiteBoss_Sword_HeadShot}
      lists: {}
    BodyParamList: !list
      objects:
        BodyParam_0: !obj {RigidName: !str64 Ragdoll_Arm_1_L, FrictionScale: 0.7,
          BuoyancyScale: 1.0}
        BodyParam_1: !obj {RigidName: !str64 Ragdoll_Arm_1_R, FrictionScale: 0.7,
          BuoyancyScale: 1.0}
        BodyParam_2: !obj {RigidName: !str64 Ragdoll_Arm_2_L, FrictionScale: 0.7,
          BuoyancyScale: 1.0}
        BodyParam_3: !obj {RigidName: !str64 Ragdoll_Arm_2_R, FrictionScale: 0.7,
          BuoyancyScale: 1.0}
        BodyParam_4: !obj {RigidName: !str64 Ragdoll_Head, FrictionScale: 0.6, BuoyancyScale: 1.0}
        BodyParam_5: !obj {RigidName: !str64 Ragdoll_Skl_Root, FrictionScale: 0.6,
          BuoyancyScale: 1.0}
        BodyParam_6: !obj {RigidName: !str64 Ragdoll_Spine_1, FrictionScale: 0.6,
          BuoyancyScale: 1.0}
        BodyParam_7: !obj {RigidName: !str64 Ragdoll_Spine_2, FrictionScale: 1.0,
          BuoyancyScale: 1.0}
        BodyParam_8: !obj {RigidName: !str64 Ragdoll_Wrist_R, FrictionScale: 0.7,
          BuoyancyScale: 1.0}
      lists: {}
