!io
version: 0
type: xml
param_root: !list
  objects:
    CommonData: !obj {UpperLimitHight: 0.7, LowerLimitHight: -1.25}
  lists:
    ImpulseParamList: !list
      objects:
        ImpulseParam_Default: !obj {FileName: !str64 Lynel_Default}
        ImpulseParam_Sword: !obj {FileName: !str64 Lynel_Sword}
        ImpulseParam_Arrow: !obj {FileName: !str64 Lynel_Arrow}
        ImpulseParam_HeadShot: !obj {FileName: !str64 Lynel_HeadShot}
        ImpulseParam_LargeSword: !obj {FileName: !str64 Lynel_LargeSword}
        ImpulseParam_Spear: !obj {FileName: !str64 Lynel_Spear}
        ImpulseParam_Bomb: !obj {FileName: !str64 Lynel_Bomb}
        ImpulseParam_ShockWave: !obj {FileName: !str64 Lynel_ShockWave}
        ImpulseParam_Gust: !obj {FileName: !str64 Lynel_Gust}
      lists: {}
    BodyParamList: !list
      objects:
        BodyParam_0: !obj {RigidName: !str64 Ragdoll_Head, FrictionScale: 1.0, BuoyancyScale: 1.0}
        BodyParam_1: !obj {RigidName: !str64 Ragdoll_Man_Arm_1_L, FrictionScale: 0.5,
          BuoyancyScale: 1.0}
        BodyParam_2: !obj {RigidName: !str64 Ragdoll_Man_Arm_1_R, FrictionScale: 0.5,
          BuoyancyScale: 1.0}
        BodyParam_3: !obj {RigidName: !str64 Ragdoll_Man_Arm_2_L, FrictionScale: 0.5,
          BuoyancyScale: 1.0}
        BodyParam_4: !obj {RigidName: !str64 Ragdoll_Man_Arm_2_R, FrictionScale: 0.5,
          BuoyancyScale: 1.0}
        BodyParam_5: !obj {RigidName: !str64 Ragdoll_Man_Spine_1, FrictionScale: 1.0,
          BuoyancyScale: 1.0}
        BodyParam_6: !obj {RigidName: !str64 Ragdoll_Man_Spine_2, FrictionScale: 1.0,
          BuoyancyScale: 1.0}
        BodyParam_7: !obj {RigidName: !str64 Ragdoll_Man_Wrist_L, FrictionScale: 0.5,
          BuoyancyScale: 1.0}
        BodyParam_8: !obj {RigidName: !str64 Ragdoll_Man_Wrist_R, FrictionScale: 0.5,
          BuoyancyScale: 1.0}
        BodyParam_9: !obj {RigidName: !str64 Ragdoll_Spine_2, FrictionScale: 1.0,
          BuoyancyScale: 1.0}
      lists: {}
